"""add unlock_level to shop_item

Revision ID: 2ea1435d61c6
Revises: 33ef8425a5ad
Create Date: 2026-08-11 17:01:00.984284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea1435d61c6'
down_revision: Union[str, Sequence[str], None] = '33ef8425a5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopitem', sa.Column('unlock_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shopitem_unlock_level'), 'shopitem', ['unlock_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopitem_unlock_level'), table_name='shopitem')
    op.drop_column('shopitem', 'unlock_level')
    # ### end Alembic commands ###
