"""add points, shop_items, user_inventory tables

Revision ID: 33ef8425a5ad
Revises: 
Create Date: 2026-08-11 16:29:31.770075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '33ef8425a5ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopitem',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_purchasable', sa.Boolean(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('pointtransaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pointtransaction_created_at'), 'pointtransaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_pointtransaction_user_id'), 'pointtransaction', ['user_id'], unique=False)
    op.create_table('userinventory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquired_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shopitem.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinventory_item_id'), 'userinventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_userinventory_user_id'), 'userinventory', ['user_id'], unique=False)
    op.add_column('user', sa.Column('current_points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_points')
    op.drop_index(op.f('ix_userinventory_user_id'), table_name='userinventory')
    op.drop_index(op.f('ix_userinventory_item_id'), table_name='userinventory')
    op.drop_table('userinventory')
    op.drop_index(op.f('ix_pointtransaction_user_id'), table_name='pointtransaction')
    op.drop_index(op.f('ix_pointtransaction_created_at'), table_name='pointtransaction')
    op.drop_table('pointtransaction')
    op.drop_table('shopitem')
    # ### end Alembic commands ###
