"""add completed_at to daily_challenge

Revision ID: 56a045df69db
Revises: df63c8caff8c
Create Date: 2026-09-03 15:48:48.219835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a045df69db'
down_revision: Union[str, Sequence[str], None] = 'df63c8caff8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailychallenge', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailychallenge', 'completed_at')
    # ### end Alembic commands ###
