"""add reward_snapshot to daily_challenge

Revision ID: df63c8caff8c
Revises: 2ea1435d61c6
Create Date: 2026-08-23 11:04:19.687421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df63c8caff8c'
down_revision: Union[str, Sequence[str], None] = '2ea1435d61c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailychallenge', sa.Column('reward_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailychallenge', 'reward_snapshot')
    # ### end Alembic commands ###
