import { Transaction } from '@/constants/mockTypes';

export const mockTransactions: Transaction[] = [
  {
    tx_id: 'tx-001',
    user_id: 'user-demo-001',
    tx_date: '2026-05-19',
    tx_time: '08:45',
    amount: 5800,
    merchant_name: '스타벅스',
    mydata_category: '식비',
    final_category: '카페',
    is_user_corrected: true,
  },
  {
    tx_id: 'tx-002',
    user_id: 'user-demo-001',
    tx_date: '2026-05-19',
    tx_time: '12:25',
    amount: 9200,
    merchant_name: '김밥천국',
    mydata_category: '식비',
    final_category: '식비',
    is_user_corrected: false,
  },
  {
    tx_id: 'tx-003',
    user_id: 'user-demo-001',
    tx_date: '2026-05-18',
    tx_time: '19:10',
    amount: 16800,
    merchant_name: '무신사',
    mydata_category: '쇼핑',
    final_category: '쇼핑',
    is_user_corrected: false,
  },
  {
    tx_id: 'tx-004',
    user_id: 'user-demo-001',
    tx_date: '2026-05-18',
    tx_time: '14:30',
    amount: 4500,
    merchant_name: '메가커피',
    mydata_category: '식비',
    final_category: '카페',
    is_user_corrected: true,
  },
  {
    tx_id: 'tx-005',
    user_id: 'user-demo-001',
    tx_date: '2026-05-17',
    tx_time: '22:05',
    amount: 14500,
    merchant_name: '배달의민족',
    mydata_category: '식비',
    final_category: '식비',
    is_user_corrected: false,
  },
  {
    tx_id: 'tx-006',
    user_id: 'user-demo-001',
    tx_date: '2026-05-17',
    tx_time: '09:12',
    amount: 1550,
    merchant_name: '지하철',
    mydata_category: '교통',
    final_category: '교통',
    is_user_corrected: false,
  },
];